name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.12'}
    - run: pip install customtkinter pymupdf pyinstaller
    - uses: mlugg/setup-zig@v1
      with: {version: 0.11.0}
    - run: zig build-lib parser_core.zig -dynamic -O ReleaseFast
    - run: pyinstaller --noconsole --onefile --add-data "parser_core.dll;." --name "Rwandan_Law_Parser" app.py
    - uses: actions/upload-artifact@v4
      with: {name: Windows_Parser, path: dist/Rwandan_Law_Parser.exe}
